#!/bin/bash
export PATH=$(dirname "${BASH_SOURCE[0]}"):/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

letsencrypt_domains_file=$(dirname "${BASH_SOURCE[0]}")/letsencrypt-domains

while :; do
    ok=1

    while read domains; do
        letsencrypt-setup $domains || ok=0
    done < <(cat "$letsencrypt_domains_file" | sed '/^$/d;/^#/d')

    if [ "$ok" != 1 ]; then
        account="$(whoami)@$(hostname)"
        mail -s "Let's Encrypt just failed on $account" "$account" <<< "Let's Encrypt just failed to generate one or more certificates on $account."
    fi
    sleep 86400
done
